apiVersion: v1
kind: ResourceQuota
metadata:
  name: submissions
  namespace: submissions
spec:
  hard:
    pods: "16"
    requests.cpu: "8"
    requests.memory: "8Gi"
    limits.cpu: "16"
    limits.memory: "16Gi"
