// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ironbook/v1/order_intake.proto

package ironbookv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderIntake_Submit_FullMethodName = "/ironbook.v1.OrderIntake/Submit"
)

// OrderIntakeClient is the client API for OrderIntake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderIntake is the wire contract that the reference-oracle (and every
// contestant submission) exposes. The fairness-gateway forwards every
// NormalizedOrder to both the submission and the oracle in parallel.
type OrderIntakeClient interface {
	Submit(ctx context.Context, in *NormalizedOrder, opts ...grpc.CallOption) (*Reply, error)
}

type orderIntakeClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderIntakeClient(cc grpc.ClientConnInterface) OrderIntakeClient {
	return &orderIntakeClient{cc}
}

func (c *orderIntakeClient) Submit(ctx context.Context, in *NormalizedOrder, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, OrderIntake_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderIntakeServer is the server API for OrderIntake service.
// All implementations should embed UnimplementedOrderIntakeServer
// for forward compatibility.
//
// OrderIntake is the wire contract that the reference-oracle (and every
// contestant submission) exposes. The fairness-gateway forwards every
// NormalizedOrder to both the submission and the oracle in parallel.
type OrderIntakeServer interface {
	Submit(context.Context, *NormalizedOrder) (*Reply, error)
}

// UnimplementedOrderIntakeServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderIntakeServer struct{}

func (UnimplementedOrderIntakeServer) Submit(context.Context, *NormalizedOrder) (*Reply, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedOrderIntakeServer) testEmbeddedByValue() {}

// UnsafeOrderIntakeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderIntakeServer will
// result in compilation errors.
type UnsafeOrderIntakeServer interface {
	mustEmbedUnimplementedOrderIntakeServer()
}

func RegisterOrderIntakeServer(s grpc.ServiceRegistrar, srv OrderIntakeServer) {
	// If the following call panics, it indicates UnimplementedOrderIntakeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderIntake_ServiceDesc, srv)
}

func _OrderIntake_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NormalizedOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderIntakeServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderIntake_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderIntakeServer).Submit(ctx, req.(*NormalizedOrder))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderIntake_ServiceDesc is the grpc.ServiceDesc for OrderIntake service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderIntake_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ironbook.v1.OrderIntake",
	HandlerType: (*OrderIntakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _OrderIntake_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ironbook/v1/order_intake.proto",
}
