// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ironbook/v1/order_intake.proto

package ironbookv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reply bundles the per-order ack with the resulting fills.
type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *Ack                   `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Fills         []*Fill                `protobuf:"bytes,2,rep,name=fills,proto3" json:"fills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_ironbook_v1_order_intake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_ironbook_v1_order_intake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_ironbook_v1_order_intake_proto_rawDescGZIP(), []int{0}
}

func (x *Reply) GetAck() *Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *Reply) GetFills() []*Fill {
	if x != nil {
		return x.Fills
	}
	return nil
}

var File_ironbook_v1_order_intake_proto protoreflect.FileDescriptor

const file_ironbook_v1_order_intake_proto_rawDesc = "" +
	"\n" +
	"\x1eironbook/v1/order_intake.proto\x12\vironbook.v1\x1a\x18ironbook/v1/orders.proto\"T\n" +
	"\x05Reply\x12\"\n" +
	"\x03ack\x18\x01 \x01(\v2\x10.ironbook.v1.AckR\x03ack\x12'\n" +
	"\x05fills\x18\x02 \x03(\v2\x11.ironbook.v1.FillR\x05fills2I\n" +
	"\vOrderIntake\x12:\n" +
	"\x06Submit\x12\x1c.ironbook.v1.NormalizedOrder\x1a\x12.ironbook.v1.ReplyBDZBgithub.com/KartikMehra22/IronBook/pkg/proto/ironbook/v1;ironbookv1b\x06proto3"

var (
	file_ironbook_v1_order_intake_proto_rawDescOnce sync.Once
	file_ironbook_v1_order_intake_proto_rawDescData []byte
)

func file_ironbook_v1_order_intake_proto_rawDescGZIP() []byte {
	file_ironbook_v1_order_intake_proto_rawDescOnce.Do(func() {
		file_ironbook_v1_order_intake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ironbook_v1_order_intake_proto_rawDesc), len(file_ironbook_v1_order_intake_proto_rawDesc)))
	})
	return file_ironbook_v1_order_intake_proto_rawDescData
}

var file_ironbook_v1_order_intake_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ironbook_v1_order_intake_proto_goTypes = []any{
	(*Reply)(nil),           // 0: ironbook.v1.Reply
	(*Ack)(nil),             // 1: ironbook.v1.Ack
	(*Fill)(nil),            // 2: ironbook.v1.Fill
	(*NormalizedOrder)(nil), // 3: ironbook.v1.NormalizedOrder
}
var file_ironbook_v1_order_intake_proto_depIdxs = []int32{
	1, // 0: ironbook.v1.Reply.ack:type_name -> ironbook.v1.Ack
	2, // 1: ironbook.v1.Reply.fills:type_name -> ironbook.v1.Fill
	3, // 2: ironbook.v1.OrderIntake.Submit:input_type -> ironbook.v1.NormalizedOrder
	0, // 3: ironbook.v1.OrderIntake.Submit:output_type -> ironbook.v1.Reply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ironbook_v1_order_intake_proto_init() }
func file_ironbook_v1_order_intake_proto_init() {
	if File_ironbook_v1_order_intake_proto != nil {
		return
	}
	file_ironbook_v1_orders_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ironbook_v1_order_intake_proto_rawDesc), len(file_ironbook_v1_order_intake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ironbook_v1_order_intake_proto_goTypes,
		DependencyIndexes: file_ironbook_v1_order_intake_proto_depIdxs,
		MessageInfos:      file_ironbook_v1_order_intake_proto_msgTypes,
	}.Build()
	File_ironbook_v1_order_intake_proto = out.File
	file_ironbook_v1_order_intake_proto_goTypes = nil
	file_ironbook_v1_order_intake_proto_depIdxs = nil
}
