// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ironbook/v1/orders.proto

package ironbookv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Buf STANDARD lint requires every enum value to be prefixed with the enum
// name in SCREAMING_SNAKE_CASE.
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BID         Side = 1
	Side_SIDE_ASK         Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BID",
		2: "SIDE_ASK",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BID":         1,
		"SIDE_ASK":         2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_ironbook_v1_orders_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_ironbook_v1_orders_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_ironbook_v1_orders_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_LIMIT",
		2: "ORDER_TYPE_MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_LIMIT":       1,
		"ORDER_TYPE_MARKET":      2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_ironbook_v1_orders_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_ironbook_v1_orders_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_ironbook_v1_orders_proto_rawDescGZIP(), []int{1}
}

type TimeInForce int32

const (
	TimeInForce_TIME_IN_FORCE_UNSPECIFIED TimeInForce = 0
	TimeInForce_TIME_IN_FORCE_GTC         TimeInForce = 1
	TimeInForce_TIME_IN_FORCE_IOC         TimeInForce = 2
	TimeInForce_TIME_IN_FORCE_FOK         TimeInForce = 3
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "TIME_IN_FORCE_UNSPECIFIED",
		1: "TIME_IN_FORCE_GTC",
		2: "TIME_IN_FORCE_IOC",
		3: "TIME_IN_FORCE_FOK",
	}
	TimeInForce_value = map[string]int32{
		"TIME_IN_FORCE_UNSPECIFIED": 0,
		"TIME_IN_FORCE_GTC":         1,
		"TIME_IN_FORCE_IOC":         2,
		"TIME_IN_FORCE_FOK":         3,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_ironbook_v1_orders_proto_enumTypes[2].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_ironbook_v1_orders_proto_enumTypes[2]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_ironbook_v1_orders_proto_rawDescGZIP(), []int{2}
}

type NormalizedOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformSeq   uint64                 `protobuf:"varint,1,opt,name=platform_seq,json=platformSeq,proto3" json:"platform_seq,omitempty"`
	PlatformTsNs  uint64                 `protobuf:"varint,2,opt,name=platform_ts_ns,json=platformTsNs,proto3" json:"platform_ts_ns,omitempty"`
	ClientOrderId []byte                 `protobuf:"bytes,3,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"` // u128 packed (bot_id, local_seq)
	SessionToken  []byte                 `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`      // 32 bytes opaque
	Side          Side                   `protobuf:"varint,5,opt,name=side,proto3,enum=ironbook.v1.Side" json:"side,omitempty"`
	Qty           uint64                 `protobuf:"varint,6,opt,name=qty,proto3" json:"qty,omitempty"`
	Price         int64                  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"` // ticks; integer math
	OrderType     OrderType              `protobuf:"varint,8,opt,name=order_type,json=orderType,proto3,enum=ironbook.v1.OrderType" json:"order_type,omitempty"`
	Tif           TimeInForce            `protobuf:"varint,9,opt,name=tif,proto3,enum=ironbook.v1.TimeInForce" json:"tif,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedOrder) Reset() {
	*x = NormalizedOrder{}
	mi := &file_ironbook_v1_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedOrder) ProtoMessage() {}

func (x *NormalizedOrder) ProtoReflect() protoreflect.Message {
	mi := &file_ironbook_v1_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedOrder.ProtoReflect.Descriptor instead.
func (*NormalizedOrder) Descriptor() ([]byte, []int) {
	return file_ironbook_v1_orders_proto_rawDescGZIP(), []int{0}
}

func (x *NormalizedOrder) GetPlatformSeq() uint64 {
	if x != nil {
		return x.PlatformSeq
	}
	return 0
}

func (x *NormalizedOrder) GetPlatformTsNs() uint64 {
	if x != nil {
		return x.PlatformTsNs
	}
	return 0
}

func (x *NormalizedOrder) GetClientOrderId() []byte {
	if x != nil {
		return x.ClientOrderId
	}
	return nil
}

func (x *NormalizedOrder) GetSessionToken() []byte {
	if x != nil {
		return x.SessionToken
	}
	return nil
}

func (x *NormalizedOrder) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *NormalizedOrder) GetQty() uint64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *NormalizedOrder) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *NormalizedOrder) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *NormalizedOrder) GetTif() TimeInForce {
	if x != nil {
		return x.Tif
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformSeq   uint64                 `protobuf:"varint,1,opt,name=platform_seq,json=platformSeq,proto3" json:"platform_seq,omitempty"`
	AckTsNs       uint64                 `protobuf:"varint,2,opt,name=ack_ts_ns,json=ackTsNs,proto3" json:"ack_ts_ns,omitempty"`
	Status        uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"` // 0 = ok
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_ironbook_v1_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_ironbook_v1_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_ironbook_v1_orders_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetPlatformSeq() uint64 {
	if x != nil {
		return x.PlatformSeq
	}
	return 0
}

func (x *Ack) GetAckTsNs() uint64 {
	if x != nil {
		return x.AckTsNs
	}
	return 0
}

func (x *Ack) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Fill struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TradeId          uint64                 `protobuf:"varint,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	PlatformSeqTaker uint64                 `protobuf:"varint,2,opt,name=platform_seq_taker,json=platformSeqTaker,proto3" json:"platform_seq_taker,omitempty"`
	PlatformSeqMaker uint64                 `protobuf:"varint,3,opt,name=platform_seq_maker,json=platformSeqMaker,proto3" json:"platform_seq_maker,omitempty"`
	Price            int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Qty              uint64                 `protobuf:"varint,5,opt,name=qty,proto3" json:"qty,omitempty"`
	TsNs             uint64                 `protobuf:"varint,6,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Fill) Reset() {
	*x = Fill{}
	mi := &file_ironbook_v1_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fill) ProtoMessage() {}

func (x *Fill) ProtoReflect() protoreflect.Message {
	mi := &file_ironbook_v1_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fill.ProtoReflect.Descriptor instead.
func (*Fill) Descriptor() ([]byte, []int) {
	return file_ironbook_v1_orders_proto_rawDescGZIP(), []int{2}
}

func (x *Fill) GetTradeId() uint64 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

func (x *Fill) GetPlatformSeqTaker() uint64 {
	if x != nil {
		return x.PlatformSeqTaker
	}
	return 0
}

func (x *Fill) GetPlatformSeqMaker() uint64 {
	if x != nil {
		return x.PlatformSeqMaker
	}
	return 0
}

func (x *Fill) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Fill) GetQty() uint64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Fill) GetTsNs() uint64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

var File_ironbook_v1_orders_proto protoreflect.FileDescriptor

const file_ironbook_v1_orders_proto_rawDesc = "" +
	"\n" +
	"\x18ironbook/v1/orders.proto\x12\vironbook.v1\"\xd9\x02\n" +
	"\x0fNormalizedOrder\x12!\n" +
	"\fplatform_seq\x18\x01 \x01(\x04R\vplatformSeq\x12$\n" +
	"\x0eplatform_ts_ns\x18\x02 \x01(\x04R\fplatformTsNs\x12&\n" +
	"\x0fclient_order_id\x18\x03 \x01(\fR\rclientOrderId\x12#\n" +
	"\rsession_token\x18\x04 \x01(\fR\fsessionToken\x12%\n" +
	"\x04side\x18\x05 \x01(\x0e2\x11.ironbook.v1.SideR\x04side\x12\x10\n" +
	"\x03qty\x18\x06 \x01(\x04R\x03qty\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\x125\n" +
	"\n" +
	"order_type\x18\b \x01(\x0e2\x16.ironbook.v1.OrderTypeR\torderType\x12*\n" +
	"\x03tif\x18\t \x01(\x0e2\x18.ironbook.v1.TimeInForceR\x03tif\"v\n" +
	"\x03Ack\x12!\n" +
	"\fplatform_seq\x18\x01 \x01(\x04R\vplatformSeq\x12\x1a\n" +
	"\tack_ts_ns\x18\x02 \x01(\x04R\aackTsNs\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xba\x01\n" +
	"\x04Fill\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\x04R\atradeId\x12,\n" +
	"\x12platform_seq_taker\x18\x02 \x01(\x04R\x10platformSeqTaker\x12,\n" +
	"\x12platform_seq_maker\x18\x03 \x01(\x04R\x10platformSeqMaker\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x10\n" +
	"\x03qty\x18\x05 \x01(\x04R\x03qty\x12\x13\n" +
	"\x05ts_ns\x18\x06 \x01(\x04R\x04tsNs*8\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BID\x10\x01\x12\f\n" +
	"\bSIDE_ASK\x10\x02*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x02*q\n" +
	"\vTimeInForce\x12\x1d\n" +
	"\x19TIME_IN_FORCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TIME_IN_FORCE_GTC\x10\x01\x12\x15\n" +
	"\x11TIME_IN_FORCE_IOC\x10\x02\x12\x15\n" +
	"\x11TIME_IN_FORCE_FOK\x10\x03BDZBgithub.com/KartikMehra22/IronBook/pkg/proto/ironbook/v1;ironbookv1b\x06proto3"

var (
	file_ironbook_v1_orders_proto_rawDescOnce sync.Once
	file_ironbook_v1_orders_proto_rawDescData []byte
)

func file_ironbook_v1_orders_proto_rawDescGZIP() []byte {
	file_ironbook_v1_orders_proto_rawDescOnce.Do(func() {
		file_ironbook_v1_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ironbook_v1_orders_proto_rawDesc), len(file_ironbook_v1_orders_proto_rawDesc)))
	})
	return file_ironbook_v1_orders_proto_rawDescData
}

var file_ironbook_v1_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ironbook_v1_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ironbook_v1_orders_proto_goTypes = []any{
	(Side)(0),               // 0: ironbook.v1.Side
	(OrderType)(0),          // 1: ironbook.v1.OrderType
	(TimeInForce)(0),        // 2: ironbook.v1.TimeInForce
	(*NormalizedOrder)(nil), // 3: ironbook.v1.NormalizedOrder
	(*Ack)(nil),             // 4: ironbook.v1.Ack
	(*Fill)(nil),            // 5: ironbook.v1.Fill
}
var file_ironbook_v1_orders_proto_depIdxs = []int32{
	0, // 0: ironbook.v1.NormalizedOrder.side:type_name -> ironbook.v1.Side
	1, // 1: ironbook.v1.NormalizedOrder.order_type:type_name -> ironbook.v1.OrderType
	2, // 2: ironbook.v1.NormalizedOrder.tif:type_name -> ironbook.v1.TimeInForce
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ironbook_v1_orders_proto_init() }
func file_ironbook_v1_orders_proto_init() {
	if File_ironbook_v1_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ironbook_v1_orders_proto_rawDesc), len(file_ironbook_v1_orders_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ironbook_v1_orders_proto_goTypes,
		DependencyIndexes: file_ironbook_v1_orders_proto_depIdxs,
		EnumInfos:         file_ironbook_v1_orders_proto_enumTypes,
		MessageInfos:      file_ironbook_v1_orders_proto_msgTypes,
	}.Build()
	File_ironbook_v1_orders_proto = out.File
	file_ironbook_v1_orders_proto_goTypes = nil
	file_ironbook_v1_orders_proto_depIdxs = nil
}
