// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ironbook/v1/runs.proto

package ironbookv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BenchmarkRunRef struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RunId            []byte                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // 16 bytes UUID v7
	ScenarioHash     string                 `protobuf:"bytes,2,opt,name=scenario_hash,json=scenarioHash,proto3" json:"scenario_hash,omitempty"`
	SubmissionSha256 string                 `protobuf:"bytes,3,opt,name=submission_sha256,json=submissionSha256,proto3" json:"submission_sha256,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BenchmarkRunRef) Reset() {
	*x = BenchmarkRunRef{}
	mi := &file_ironbook_v1_runs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkRunRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkRunRef) ProtoMessage() {}

func (x *BenchmarkRunRef) ProtoReflect() protoreflect.Message {
	mi := &file_ironbook_v1_runs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkRunRef.ProtoReflect.Descriptor instead.
func (*BenchmarkRunRef) Descriptor() ([]byte, []int) {
	return file_ironbook_v1_runs_proto_rawDescGZIP(), []int{0}
}

func (x *BenchmarkRunRef) GetRunId() []byte {
	if x != nil {
		return x.RunId
	}
	return nil
}

func (x *BenchmarkRunRef) GetScenarioHash() string {
	if x != nil {
		return x.ScenarioHash
	}
	return ""
}

func (x *BenchmarkRunRef) GetSubmissionSha256() string {
	if x != nil {
		return x.SubmissionSha256
	}
	return ""
}

var File_ironbook_v1_runs_proto protoreflect.FileDescriptor

const file_ironbook_v1_runs_proto_rawDesc = "" +
	"\n" +
	"\x16ironbook/v1/runs.proto\x12\vironbook.v1\"z\n" +
	"\x0fBenchmarkRunRef\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\fR\x05runId\x12#\n" +
	"\rscenario_hash\x18\x02 \x01(\tR\fscenarioHash\x12+\n" +
	"\x11submission_sha256\x18\x03 \x01(\tR\x10submissionSha256BDZBgithub.com/KartikMehra22/IronBook/pkg/proto/ironbook/v1;ironbookv1b\x06proto3"

var (
	file_ironbook_v1_runs_proto_rawDescOnce sync.Once
	file_ironbook_v1_runs_proto_rawDescData []byte
)

func file_ironbook_v1_runs_proto_rawDescGZIP() []byte {
	file_ironbook_v1_runs_proto_rawDescOnce.Do(func() {
		file_ironbook_v1_runs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ironbook_v1_runs_proto_rawDesc), len(file_ironbook_v1_runs_proto_rawDesc)))
	})
	return file_ironbook_v1_runs_proto_rawDescData
}

var file_ironbook_v1_runs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ironbook_v1_runs_proto_goTypes = []any{
	(*BenchmarkRunRef)(nil), // 0: ironbook.v1.BenchmarkRunRef
}
var file_ironbook_v1_runs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ironbook_v1_runs_proto_init() }
func file_ironbook_v1_runs_proto_init() {
	if File_ironbook_v1_runs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ironbook_v1_runs_proto_rawDesc), len(file_ironbook_v1_runs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ironbook_v1_runs_proto_goTypes,
		DependencyIndexes: file_ironbook_v1_runs_proto_depIdxs,
		MessageInfos:      file_ironbook_v1_runs_proto_msgTypes,
	}.Build()
	File_ironbook_v1_runs_proto = out.File
	file_ironbook_v1_runs_proto_goTypes = nil
	file_ironbook_v1_runs_proto_depIdxs = nil
}
