// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ironbook/v1/time.proto

package ironbookv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NextStampsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of (seq, ts) stamps to reserve. Clamped to [1, 65535] by the
	// server. The server reserves a contiguous block; the client emits them
	// sequentially.
	BatchSize     uint32 `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextStampsRequest) Reset() {
	*x = NextStampsRequest{}
	mi := &file_ironbook_v1_time_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextStampsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextStampsRequest) ProtoMessage() {}

func (x *NextStampsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironbook_v1_time_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextStampsRequest.ProtoReflect.Descriptor instead.
func (*NextStampsRequest) Descriptor() ([]byte, []int) {
	return file_ironbook_v1_time_proto_rawDescGZIP(), []int{0}
}

func (x *NextStampsRequest) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type NextStampsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First sequence number of the reserved range, inclusive.
	FirstSeq uint64 `protobuf:"varint,1,opt,name=first_seq,json=firstSeq,proto3" json:"first_seq,omitempty"`
	// First nanosecond timestamp corresponding to first_seq.
	FirstTsNs uint64 `protobuf:"varint,2,opt,name=first_ts_ns,json=firstTsNs,proto3" json:"first_ts_ns,omitempty"`
	// Suggested nanosecond spacing for client-local interpolation.
	StepNs uint64 `protobuf:"varint,3,opt,name=step_ns,json=stepNs,proto3" json:"step_ns,omitempty"`
	// Actual batch size granted (== request.batch_size after clamping).
	BatchSize     uint32 `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextStampsResponse) Reset() {
	*x = NextStampsResponse{}
	mi := &file_ironbook_v1_time_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextStampsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextStampsResponse) ProtoMessage() {}

func (x *NextStampsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironbook_v1_time_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextStampsResponse.ProtoReflect.Descriptor instead.
func (*NextStampsResponse) Descriptor() ([]byte, []int) {
	return file_ironbook_v1_time_proto_rawDescGZIP(), []int{1}
}

func (x *NextStampsResponse) GetFirstSeq() uint64 {
	if x != nil {
		return x.FirstSeq
	}
	return 0
}

func (x *NextStampsResponse) GetFirstTsNs() uint64 {
	if x != nil {
		return x.FirstTsNs
	}
	return 0
}

func (x *NextStampsResponse) GetStepNs() uint64 {
	if x != nil {
		return x.StepNs
	}
	return 0
}

func (x *NextStampsResponse) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

var File_ironbook_v1_time_proto protoreflect.FileDescriptor

const file_ironbook_v1_time_proto_rawDesc = "" +
	"\n" +
	"\x16ironbook/v1/time.proto\x12\vironbook.v1\"2\n" +
	"\x11NextStampsRequest\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x01 \x01(\rR\tbatchSize\"\x89\x01\n" +
	"\x12NextStampsResponse\x12\x1b\n" +
	"\tfirst_seq\x18\x01 \x01(\x04R\bfirstSeq\x12\x1e\n" +
	"\vfirst_ts_ns\x18\x02 \x01(\x04R\tfirstTsNs\x12\x17\n" +
	"\astep_ns\x18\x03 \x01(\x04R\x06stepNs\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\rR\tbatchSize2\\\n" +
	"\vTimeService\x12M\n" +
	"\n" +
	"NextStamps\x12\x1e.ironbook.v1.NextStampsRequest\x1a\x1f.ironbook.v1.NextStampsResponseBDZBgithub.com/KartikMehra22/IronBook/pkg/proto/ironbook/v1;ironbookv1b\x06proto3"

var (
	file_ironbook_v1_time_proto_rawDescOnce sync.Once
	file_ironbook_v1_time_proto_rawDescData []byte
)

func file_ironbook_v1_time_proto_rawDescGZIP() []byte {
	file_ironbook_v1_time_proto_rawDescOnce.Do(func() {
		file_ironbook_v1_time_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ironbook_v1_time_proto_rawDesc), len(file_ironbook_v1_time_proto_rawDesc)))
	})
	return file_ironbook_v1_time_proto_rawDescData
}

var file_ironbook_v1_time_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ironbook_v1_time_proto_goTypes = []any{
	(*NextStampsRequest)(nil),  // 0: ironbook.v1.NextStampsRequest
	(*NextStampsResponse)(nil), // 1: ironbook.v1.NextStampsResponse
}
var file_ironbook_v1_time_proto_depIdxs = []int32{
	0, // 0: ironbook.v1.TimeService.NextStamps:input_type -> ironbook.v1.NextStampsRequest
	1, // 1: ironbook.v1.TimeService.NextStamps:output_type -> ironbook.v1.NextStampsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ironbook_v1_time_proto_init() }
func file_ironbook_v1_time_proto_init() {
	if File_ironbook_v1_time_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ironbook_v1_time_proto_rawDesc), len(file_ironbook_v1_time_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ironbook_v1_time_proto_goTypes,
		DependencyIndexes: file_ironbook_v1_time_proto_depIdxs,
		MessageInfos:      file_ironbook_v1_time_proto_msgTypes,
	}.Build()
	File_ironbook_v1_time_proto = out.File
	file_ironbook_v1_time_proto_goTypes = nil
	file_ironbook_v1_time_proto_depIdxs = nil
}
