// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ironbook/v1/time.proto

package ironbookv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimeService_NextStamps_FullMethodName = "/ironbook.v1.TimeService/NextStamps"
)

// TimeServiceClient is the client API for TimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TimeService issues monotonic (platform_seq, platform_ts_ns) stamps used by
// the fairness-gateway to label every order before it is forwarded to a
// submission or the reference oracle. Clients fetch batches (typically 10k
// at a time) to amortise the RPC.
type TimeServiceClient interface {
	NextStamps(ctx context.Context, in *NextStampsRequest, opts ...grpc.CallOption) (*NextStampsResponse, error)
}

type timeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeServiceClient(cc grpc.ClientConnInterface) TimeServiceClient {
	return &timeServiceClient{cc}
}

func (c *timeServiceClient) NextStamps(ctx context.Context, in *NextStampsRequest, opts ...grpc.CallOption) (*NextStampsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextStampsResponse)
	err := c.cc.Invoke(ctx, TimeService_NextStamps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeServiceServer is the server API for TimeService service.
// All implementations should embed UnimplementedTimeServiceServer
// for forward compatibility.
//
// TimeService issues monotonic (platform_seq, platform_ts_ns) stamps used by
// the fairness-gateway to label every order before it is forwarded to a
// submission or the reference oracle. Clients fetch batches (typically 10k
// at a time) to amortise the RPC.
type TimeServiceServer interface {
	NextStamps(context.Context, *NextStampsRequest) (*NextStampsResponse, error)
}

// UnimplementedTimeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimeServiceServer struct{}

func (UnimplementedTimeServiceServer) NextStamps(context.Context, *NextStampsRequest) (*NextStampsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NextStamps not implemented")
}
func (UnimplementedTimeServiceServer) testEmbeddedByValue() {}

// UnsafeTimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeServiceServer will
// result in compilation errors.
type UnsafeTimeServiceServer interface {
	mustEmbedUnimplementedTimeServiceServer()
}

func RegisterTimeServiceServer(s grpc.ServiceRegistrar, srv TimeServiceServer) {
	// If the following call panics, it indicates UnimplementedTimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimeService_ServiceDesc, srv)
}

func _TimeService_NextStamps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextStampsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServiceServer).NextStamps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeService_NextStamps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServiceServer).NextStamps(ctx, req.(*NextStampsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeService_ServiceDesc is the grpc.ServiceDesc for TimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ironbook.v1.TimeService",
	HandlerType: (*TimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NextStamps",
			Handler:    _TimeService_NextStamps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ironbook/v1/time.proto",
}
