apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager
  - ../../base/argocd
  - ../../base/opa-gatekeeper
  - ../../base/submissions-namespace
  - ../../base/postgres
  - ../../base/minio
  - ../../base/submission-api
