apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ironbook
resources:
  - statefulset.yaml
  - service.yaml
  - secret-template.yaml
configMapGenerator:
  - name: postgres-migrations
    files:
      - migrations/001_init.sql
      - migrations/002_submissions.sql
generatorOptions:
  disableNameSuffixHash: true
